config/routes.rb
SampleApp::Application.routes.draw do
 
  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions' }
 
  
  resources :notes, except: [:new, :index, :show] do 
    get :send_off, on: :member
    get :search, on: :collection
  end

  root to: "static_pages#home"

    
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"

  

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  theme      :string(255)
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Note < ActiveRecord::Base
  
  belongs_to :user

  validates :user_id, presence: true, numericality: { only_integer: true }
  validates :content, presence: true, length: { minimum: 1 }
  validates :theme, presence: true, length: { minimum: 1 }

  default_scope order: 'notes.created_at DESC'

end
	

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  username               :string(255)
#  timezone               :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :notes, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

   before_filter :authenticate_user!
   before_filter :detect_empty_note, only: [ :create, :update ]
   before_filter :detect_search_params, only: [:search]

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      flash[:success] = "Note created!"
      redirect_to root_url
    else
      render 'static_pages/home' 
    end
  end

  def edit
    @note = Note.find(params[:id])
    @notes = current_user.notes
    @is_edit_form = true ;
    render 'static_pages/home'
  end

  def update
    @note = Note.find(params[:id])
    @note.update_attributes(note_params)
    redirect_to root_url
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy
    redirect_to root_url
  end

  def send_off
    p "send_off ================================= "
    p params
    @note = Note.find(params[:id])
    NoteMailer.send_note(User.find(@note.user_id).email, @note).deliver
    flash[:success] = "note sended"
    redirect_to root_url
  end

  def search
    @note = Note.new
    @notes = 
      current_user.notes.find_all do |note|
        note.theme[params[:search]] || note.content[params[:search]]
      end
    render "static_pages/home"
  end

  private 
    def note_params
      params.require(:note).permit(:theme, :content)
    end

    def detect_empty_note
      #unless params[:note].blank?
        if params[:note][:theme].blank? || params[:note][:content].blank?
          flash[:notice] = "Theme or content is empty"
          redirect_to root_url
        end
      #end
    end

    def detect_search_params
      p 'detect_search_params'
      p params[:search]
      p'+++++++++++++++'
      (flash[:error] = "Bad search params"; redirect_to '/') if params[:search].blank?
    end

end

app/controllers/registrations_controller.rb
    class RegistrationsController < Devise::RegistrationsController

  def create
  	@user = User.new(user_params)
  	 if @user.save
  	 	sign_in @user
  	 	flash[:success] = "You signed up successfully"
  	 	redirect_to root_url
  	 else 
  	 	render 'new'
  	 end
  end


  def update

  	@user = User.find(current_user.id)
  	
  	new_username = params[:user][:username] 
  	unless new_username.blank?
  		@user.update_attributes(username: new_username) unless new_username == @user.username
  	end	

  	new_timezone = params[:user][:timezone]
	 		@user.update_attributes(timezone: new_timezone) unless new_timezone == @user.timezone
  	  	
   	super
  
  end


 private
 	def user_params
 		params.require(:user).permit(:username, :email, :password, :password_confirmation, :timezone)
 	end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @note = current_user ? Note.new : nil
    @notes = current_user ? current_user.notes.paginate(page: params[:page], per_page: 5) : nil
  end

  ["help","contact","about"].each do |action|
    define_method action do; end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper

 #This method return full title 
 def full_title(page_title)
  base_title = "Ruby on Rails Tutorial Sample App"
  if page_title.empty? then
    base_title
  else 
    "#{base_title}| #{page_title}"
  end
 end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path  %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Note Manager", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li>
              <form class="navbar-search" action="/notes/search">
                <input id="search" name="search" type="text" class="search-query" placeholder="Search..."> 
              </form>
            </li>
            <li> <%= link_to "All notes", root_path %></li>
          <% else %>
            <li> <%= link_to "Home", root_path%>
          <% end %>
          <li><%= link_to "About", about_path %> </li>
          <li><%= link_to "Help", help_path %></li>
          <% if user_signed_in? %>
             <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
 <body>
  <%= render 'layouts/header'%>
     <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_note.html.erb
<li>
 	Theme: <%= note.theme %><br />
  <%= raw note.content %><br />
  <p align ='right'> Last changes <%= "#{(note.updated_at + ActiveSupport::TimeZone[current_user.timezone].utc_offset).strftime("%d/%m/%Y at %T")}"%> </p>
   <p align = 'right'> <%= link_to "", send_off_note_path(note)	, class: "icon-envelope" %> <%= link_to "" , edit_note_path(note), class: "icon-pencil" %>
    	<%= link_to "", note, class: "icon-trash", 
    																				 method: :delete,
  																					 data: { confirm: "You sure?" }%>
</li>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
  <% if user_signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= form_for(@note) do |f| %>
        
        <%= f.label :theme %>
        <%= f.text_field :theme %>

        <%= f.label :content %>
        <%= f.text_area :content %>
        
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      
      <% end %>
      </section>
    </aside>

    <% unless @notes.nil? %>
      <div class= "span9">
         <h3>notes (<%= @notes.count %>)</h3>
          <ul class="notes">  
            <%= render @notes %>
          </ul>
        </div>
    <% end %>
<% else %>
    <div class="center hero-unit">
      <h1>Welcome to the note manager</h1>

    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/shared/_create_form.html.erb
<%= form_for(@note) do |f| %>
        
	<%= f.label :theme  %>
  <%= f.text_field :theme %>

  <%= f.label :content %>
  <%= f.text_area :content %>
        
  <%= f.submit "Complete!", class: "btn btn-large btn-primary" %>
     
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_update_form.html.erb
<%= form_for(@note) do |f| %>
        
  <%= f.label :theme %>
  <%= f.text_field :theme %>

  <%= f.label :content %>
  <%= f.text_area :content %>
        
 	<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>This is about page</p>

app/views/static_pages/contact.html.erb
<%provide(:title, "Contact") %>
<h1>Sample App</h1>
<p>
Content contact page
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Sample App</h1>
<p>
  This is help page
</p>

app/views/static_pages/home.html.erb
  <% if user_signed_in? %>
  <% provide(:title, current_user.username) %>
  <div class="row">
    <aside class="span9">
      <section>
       <% unless @is_edit_form %> 
        <%= render 'shared/create_form' %>
       <% else %>
        <%= render 'shared/update_form' %>
       <% end %>
      </section>
    </aside>

    <% unless @notes.nil? %>

      
      <div class= "span9">
         <%= will_paginate @notes %> 
         <h3>notes (<%= @notes.count %>)</h3>
          <ul class="notes">  
            <%= render @notes %>
          </ul>
        </div>

    <% end %>


  <% else %>
    <% provide(:title, "Home") %>
    <div class="center hero-unit">
      <h1>Welcome to the note manager</h1>

    <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, " #{current_user.username} Personal page") %>
  <div class="span8">
    <%= "#{@user.email}" %>
  </div>
  <div class="span8">
    <% if @user.notes.any? %>
      <h3>notes (<%= @user.notes.count %>)</h3>
      <ol class="notes">
        <%= render @notes %>
      </ol>
      <% end %>
  </div>
</div>